### PR TITLE
Impl ImplicitClone for tuples up to 12 items

### PR DESCRIPTION
**Pull request by cecton**
- Implement ImplicitClone for tuples
- Reduce number of dependencies and increase tuples to 12 items

### CODE REVIEW

**Comment by cecton** [comment]
(clippy issues are being fixed in another PR)

**Comment by cecton** [comment]
I guess I will merge this for now as it does not sound really critical anyway. I don't want the review process to be a burden for anyone.

**Review by WorldSEnder — APPROVED** [review]
Looks good to me. Following the std lib for the limit of 12 sounds like a good idea.

**Comment by cecton** [comment]
Thank you for the review :pray:

**Pull request merged**
