### PR TITLE
Add Serialize/Deserialize implementations

### PR DESCRIPTION
**Pull request by uzytkownik**

### CODE REVIEW

**Comment by FlorianUekermann** [comment]
@cecton : Any reason this can't be merged?

**Comment by cecton** [comment]
Probably the only reason is that I missed it sorry ^_^ ... looking into it now

**Review by cecton — APPROVED** [review]

**Comment by cecton** [comment]
Yup looks perfect :ok_hand: thank your for your contribution!

**Comment by cecton** [comment]
Released in 0.3.6

**Pull request merged**
