### PR TITLE
Update Indexmap Dependency and Enable Dependabot.

### PR DESCRIPTION
**Pull request by futursolo**
This pull request:

- updates the indexmap dependency
- enables Dependabot.
- updates the MSRV to 1.64 (due to indexmap).

### CODE REVIEW

**Comment by futursolo** [comment]
@cecton

Could you please review this and release a new version with the updated dependency?
This is blocking https://github.com/yewstack/yew/pull/3322.

**Review by cecton — APPROVED** [review]
doesnt seem  to be much to review ^_^

**Comment by cecton** [comment]
@futursolo to avoid getting blocked like that again, do you mind if I add you to the crate owner?

**Comment by cecton** [comment]
Released in 0.3.7

**Comment by cecton** [comment]
@futursolo do you think we should relax the version to >= 1 and <= 2?

**Comment by cecton** [comment]
I have relaxed the dependency and yield the release 0.3.7 because I think it can cause issues for yew users.

**Comment by futursolo** [comment]
@cecton

I do not think this is fixed with v0.3.8.

```
➜  stellation git:(main) ✗ cargo tree -i implicit-clone | grep -E "implicit-clone|yew"
implicit-clone v0.3.8
└── yew v0.20.0
    └── yew-router v0.17.0
➜  stellation git:(main) ✗ cargo make clippy
...
error[E0277]: the trait bound `implicit_clone::unsync::IMap<_, _>: From<indexmap::IndexMap<K, V>>` is not satisfied
   --> /Users/futursolo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yew-0.20.0/src/html/conversion.rs:204:20
    |
204 |         IMap::from(self)
    |         ---------- ^^^^ the trait `From<indexmap::IndexMap<K, V>>` is not implemented for `implicit_clone::unsync::IMap<_, _>`
    |         |
    |         required by a bound introduced by this call
    |
    = help: the following other types implement trait `From<T>`:
              <implicit_clone::unsync::IMap<K, V> as From<&'static [(K, V)]>>
              <implicit_clone::unsync::IMap<K, V> as From<indexmap::map::IndexMap<K, V>>>
              <implicit_clone::unsync::IMap<K, V> as From<std::rc::Rc<indexmap::map::IndexMap<K, V>>>>

...
For more information about this error, try `rustc --explain E0277`.
error: could not compile `yew` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
[cargo-make] ERROR - Unable to execute script.
[cargo-make] WARN - Build Failed.
```

Would it be possible to publish implicit-clone with indexmap v2 as v0.4 instead as this is a breaking change?

**Comment by cecton** [comment]
Yes I guess it creates those cases where you need to set a specific version in your lockfile. I had the same issue with serde and the likes recently on a different project. https://github.com/rust-disk-partition-management/gptman/pull/112/files

I'll bump the minor and yank that one.

**Comment by cecton** [comment]
I yanked 0.3.8. So only 0.3.6 is still available with indexmap 1.x. And I released 0.4.0 which has indexmap 2.x

**Pull request merged**
